#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

# Compiling libraries and solvers
wmake libso libraries/porousInterfaceProperties/
wmake libso libraries/porousTwoPhaseProperties/
wmake libso libraries/porousImmiscibleIncompressibleTwoPhaseMixture/
wmake libso libraries/HerschelBulkleyQuemada/
wmake all libraries/porousModels
wmake all solvers/hybridBiotInterFoam
